version: '3.7'

services:
  frontend:
    image: 'validation-frontend-dev'
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - react:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  react:
  node_modules: